# 課題 3-2
4 年　1組 22番 213380021 仲戸川凱<br><br>
課題前に`numpy`をインポートする。


In [4]:
# import lib
import numpy as np

以下の数式を使って以下の処理を行う。
$$
A = \left( \begin{array}{cc} 5 & 3 & 7 \\ 6 & 8 & 4 \\ 0 & 5 & 1 \end{array} \right) 
$$

## Q1.上記の行列$A$をリスト型配列で作成し、配列全体と各列について、平均、分散、標準偏差を求めよ

In [43]:
def calculate_mean(data):
    return sum(data) / len(data)

def calculate_variance(data):
    mean = calculate_mean(data)
    variance = sum((x - mean) ** 2 for x in data) / len(data)
    return variance

def calculate_std_deviation(variance):
    return variance ** 0.5


A = [[5, 3, 7],
     [6, 8, 4],
     [0, 5, 1]]

all_elements = [element for row in A for element in row]
overall_mean = calculate_mean(all_elements)
overall_variance = calculate_variance(all_elements)
overall_std_deviation = calculate_std_deviation(overall_variance)

print("行列全体")
print(f"平均 : \n {overall_mean}")
print(f"分散 : \n {overall_variance}")
print(f"標準偏差 : \n {overall_std_deviation}")

print("-------------------------------------")

columns = len(A[0])
column_means = []
column_variances = []
column_std_deviations = []

for i in range(columns):
    column = [row[i] for row in A]
    column_means.append(calculate_mean(column))
    var = calculate_variance(column)
    column_variances.append(var)
    column_std_deviations.append(calculate_std_deviation(var))

print("列ごと")
print(f"平均 : \n {column_means}")
print(f"分散 : \n {column_variances}")
print(f"標準偏差 : \n {column_std_deviations}")



行列全体
平均 : 
 4.333333333333333
分散 : 
 6.222222222222221
標準偏差 : 
 2.494438257849294
-------------------------------------
列ごと
平均 : 
 [3.6666666666666665, 5.333333333333333, 4.0]
分散 : 
 [6.888888888888888, 4.222222222222222, 6.0]
標準偏差 : 
 [2.6246692913372702, 2.0548046676563256, 2.449489742783178]


## Q2.上記の行列$A$を`numpy`型配列で作成し、配列全体と各列について、平均、分散、標準偏差を求めよ

In [13]:
A = np.array([[5,3,7],
            [6,8,4],
            [0,5,1]])

print("行列全体")
print(f"平均 : \n {np.mean(A)}")
print(f"分散 : \n {A.var()}")
print(f"標準偏差 : \n {A.std()}")

print("-------------------------------------")

print("列ごと")
print(f"平均 : \n {A.mean(axis=0)}")
print(f"分散 : \n {A.var(axis=0)}")
print(f"標準偏差 : \n {A.std(axis=0)}")

行列全体
平均 : 
 4.333333333333333
分散 : 
 6.222222222222222
標準偏差 : 
 2.494438257849294
-------------------------------------
列ごと
平均 : 
 [3.66666667 5.33333333 4.        ]
分散 : 
 [6.88888889 4.22222222 6.        ]
標準偏差 : 
 [2.62466929 2.05480467 2.44948974]


## Q2.上記の行列$A$を`numpy`型配列で作成し、`numpy.where`を使って$5$以上の値を全て$-1$に置換させること。

In [16]:
A = np.array([[5,3,7],
            [6,8,4],
            [0,5,1]])

print(f"結果 : \n{np.where(A>5, -1, A)}")

結果 : 
[[ 5  3 -1]
 [-1 -1  4]
 [ 0  5  1]]
