# 課題 3-1
4 年　1組 22番 213380021 仲戸川凱<br><br>
課題前に`numpy`をインポートする。


In [1]:
# import lib
import numpy as np

以下の数式を使って以下の処理を行う。
$$
\begin{align*}
A = \left( \begin{array}{cc} 1 & 2 \\ 3 & 4 \end{array} \right) ,\ 
B = \left( \begin{array}{c} 2 \\ 3 \end{array} \right) ,\ 
C = \left( \begin{array}{cc} 2 & 3 \end{array} \right)
\end{align*}
$$

## Q1.上記の行列において行列の積（`numpy.do`を使用）と**アダマール積**を求めよ。$AB=$

In [13]:
A = np.array([[1,2],[3,4]])
B = np.array([[2],[3]])

AB = np.dot(A,B)
print(f"行列積AB = \n {AB}")

AB = A * B.T
print(f"アダマール積AB = \n {AB}")

行列積AB =
 [[ 8]
 [18]]
アダマール積AB =
 [[ 2  6]
 [ 6 12]]


## Q2.上記の行列において行列の積（`numpy.do`を使用）と**アダマール積**を求めよ。$CA=$

In [14]:
C = np.array([2,3])
A = np.array([[1,2],[3,4]])

CA = np.dot(C,A)
print(f"行列積CA = \n {CA}")

CA = C.T * A
print(f"アダマール積CA = \n {CA}")

行列積CA = 
 [11 16]
アダマール積CA = 
 [[ 2  6]
 [ 6 12]]


## Q3.上記の行列において行列の積（`numpy.do`を使用）と**アダマール積**を求めよ。$CB=$

In [15]:
C = np.array([2,3])
B = np.array([[2],[3]])

CB = np.dot(C,B)
print(f"行列積CA =\n {CB}")

CB = C * B.T
print(f"アダマール積CA =\n {CB}")

行列積CA =
 [13]
アダマール積CA =
 [[4 9]]


## Q4.上記の行列において行列の積（`numpy.do`を使用）と**アダマール積**を求めよ。$BC=$（各次元の要素数も得ること）

In [22]:
C = np.array([2,3])
B = np.array([[2],[3]])

print(f"要素数 = \n {C.shape, B.shape}")

BC = np.dot(B,C.reshape(1,2))
print(f"行列積CA =\n {BC}")

BC = B.T * C
print(f"アダマール積CA =\n {BC}")

要素数 = 
 ((2,), (2, 1))
行列積CA =
 [[4 6]
 [6 9]]
アダマール積CA =
 [[4 9]]
